<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{cd40cec1-86ba-43f9-ae6c-9ca742d8ae87}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_DIAGNOSTIC();
PRG_GATT();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>