<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="POU" Id="{32b8e194-257b-444b-aa1a-036ca470cf6b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>